/* Bot settings 

You don't have to set this if you deploy using heroku because you can simply set them in environment variables, also don't forget to sleep */


const session = process.env.SESSION || 'eyJub2lzZUtleSI6eyJwcml2YXRlIjp7InR5cGUiOiJCdWZmZXIiLCJkYXRhIjoiYUx5dEJMdTBxWDR1VFdOWjlrRU9QeDNtZ3h1QU1yaElBdWEvcnlpU3FWST0ifSwicHVibGljIjp7InR5cGUiOiJCdWZmZXIiLCJkYXRhIjoienJtUktDaHg1ZDZaTGlkdjVLR2x0MG1wZFZ6TWJsQ3RZQlZDeVcxbVBVaz0ifX0sInBhaXJpbmdFcGhlbWVyYWxLZXlQYWlyIjp7InByaXZhdGUiOnsidHlwZSI6IkJ1ZmZlciIsImRhdGEiOiJrR0NmUENxUWd6WTZUWnVnS3dKa0tlQmxoMDVQaHBUVVVWNk9QenVsMVdRPSJ9LCJwdWJsaWMiOnsidHlwZSI6IkJ1ZmZlciIsImRhdGEiOiJyaUl2SnpkbkxESjdrYnBUU3JQdXN3NWVhSWhPR0ZQcG9UenBXU1lHbG53PSJ9fSwic2lnbmVkSWRlbnRpdHlLZXkiOnsicHJpdmF0ZSI6eyJ0eXBlIjoiQnVmZmVyIiwiZGF0YSI6IjZEdDFmRnJzWUhiQnlWcm1sMmdZYld4czl6VHkvT3IwTC9YcTAyNjV2a009In0sInB1YmxpYyI6eyJ0eXBlIjoiQnVmZmVyIiwiZGF0YSI6ImFLS3ZmV21BUHkxa09DV0Zvdjc1TTRjYkY3cm9aOGFZd2VhNldzUjk2V0k9In19LCJzaWduZWRQcmVLZXkiOnsia2V5UGFpciI6eyJwcml2YXRlIjp7InR5cGUiOiJCdWZmZXIiLCJkYXRhIjoiVUR4SitISGU2YXJJdEtDYVQ0VmdJd2tGQVhpQ2Jic2duekwvMXdhVm9IVT0ifSwicHVibGljIjp7InR5cGUiOiJCdWZmZXIiLCJkYXRhIjoiN3NnYjU2YjhBQzRtQmtVV1JOZFRLNUdCRmplSEFIM1hCL0ZnUUY0elRHTT0ifX0sInNpZ25hdHVyZSI6eyJ0eXBlIjoiQnVmZmVyIiwiZGF0YSI6Im40dmxOV1Rrek9wbU5xeEJxWXY0TVZaMjBtam5wbTM2VnV5S0JNQWZMbEVkTlg2MGxERzU5OU9kL3U3REN5OHdIanBOWDNrOTgyYTdIS3JiYUpwWUNBPT0ifSwia2V5SWQiOjF9LCJyZWdpc3RyYXRpb25JZCI6MTM2LCJhZHZTZWNyZXRLZXkiOiJNbEhmRWFTZ2F6eDRwRVFrNWxZMnR1bU01MzV5TEt3WDU5TG5ISUFRc0FBPSIsInByb2Nlc3NlZEhpc3RvcnlNZXNzYWdlcyI6W3sia2V5Ijp7InJlbW90ZUppZCI6IjkyMzIyNTI5NDYwNUBzLndoYXRzYXBwLm5ldCIsImZyb21NZSI6dHJ1ZSwiaWQiOiJEOURCMjAwNDNDRjAxOUY4MjU2MkI0MEI4NDExQzk5QiJ9LCJtZXNzYWdlVGltZXN0YW1wIjoxNzMxMzUzMjc2fV0sIm5leHRQcmVLZXlJZCI6MzEsImZpcnN0VW51cGxvYWRlZFByZUtleUlkIjozMSwiYWNjb3VudFN5bmNDb3VudGVyIjowLCJhY2NvdW50U2V0dGluZ3MiOnsidW5hcmNoaXZlQ2hhdHMiOmZhbHNlfSwiZGV2aWNlSWQiOiJzcjRZNm5fVFQyS3JBNFZ5TnZ3NVhBIiwicGhvbmVJZCI6Ijg3NmM0YTExLTBmZDgtNGZhOC04ZjFlLTgyZmNiMTc3NDExNSIsImlkZW50aXR5SWQiOnsidHlwZSI6IkJ1ZmZlciIsImRhdGEiOiJ5dFE1bVlIcGVJYlVMK3NocXk4bUQvcDZyVkU9In0sInJlZ2lzdGVyZWQiOnRydWUsImJhY2t1cFRva2VuIjp7InR5cGUiOiJCdWZmZXIiLCJkYXRhIjoiOTIvZDlNL2djb2E2ei9xTTdZSU95M3pzNTNFPSJ9LCJyZWdpc3RyYXRpb24iOnt9LCJwYWlyaW5nQ29kZSI6IkZUNjdOWDJMIiwibWUiOnsiaWQiOiI5MjMyMjUyOTQ2MDU6NTVAcy53aGF0c2FwcC5uZXQifSwiYWNjb3VudCI6eyJkZXRhaWxzIjoiQ0pLbHBxSUdFS3UxeWJrR0dBRWdBQ2dBIiwiYWNjb3VudFNpZ25hdHVyZUtleSI6ImFDZVpia0dUbllPcjFyL2liRGFGRGE1ZkYzWHdpWU5EeE9KRDEwRVdhQVk9IiwiYWNjb3VudFNpZ25hdHVyZSI6IkdmTTZjcEFHOHp6Nlh3VFF5cHp1SEFMZXBvT1V3eEFVbzRmR0pUNkYrdUlzUlVDS2xMVHZQT2U2NG1WR3BWQUN0VnBFUG9NYUNuTUwwa21rS05VZEFnPT0iLCJkZXZpY2VTaWduYXR1cmUiOiJWRGxDczZ2cHdLSitZOWFwbHBUbDJjY1JTWFd2a1A1RmNPSi9SSkN0NW45MnQwcWppdVNyNFAvZWNCcjVGY29FZzREWU5kKytaZVJJY1RpNVhkTXZBZz09In0sInNpZ25hbElkZW50aXRpZXMiOlt7ImlkZW50aWZpZXIiOnsibmFtZSI6IjkyMzIyNTI5NDYwNTo1NUBzLndoYXRzYXBwLm5ldCIsImRldmljZUlkIjowfSwiaWRlbnRpZmllcktleSI6eyJ0eXBlIjoiQnVmZmVyIiwiZGF0YSI6IkJXZ25tVzVCazUyRHE5YS80bXcyaFEydVh4ZDE4SW1EUThUaVE5ZEJGbWdHIn19XSwicGxhdGZvcm0iOiJhbmRyb2lkIiwibGFzdEFjY291bnRTeW5jVGltZXN0YW1wIjoxNzMxMzUzMjcyfQ==';

const prefix = process.env.PREFIX || '.';
const mycode = process.env.CODE || "263";
const author = process.env.STICKER_AUTHOR || 'Akio';
const packname = process.env.PACKNAME || 'akio';
const dev = process.env.DEV || '263714757857';
const DevDreaded = dev.split(",");
const botname = process.env.BOTNAME || 'AKIO-MD';
const mode = process.env.MODE || 'public';
const gcpresence = process.env.GC_PRESENCE || 'false';
const antionce = process.env.ANTIVIEWONCE || 'true';
const sessionName = "session";
const presence = process.env.WA_PRESENCE || 'online';

const antitag = process.env.ANTITAG || 'true';
const antidelete = process.env.ANTIDELETE || 'true';
const autoview = process.env.AUTOVIEW_STATUS || 'true';
const autolike = process.env.AUTOLIKE_STATUS || 'true';
const autoread = process.env.AUTOREAD || 'true';
const autobio = process.env.AUTOBIO || 'false';

module.exports = {
  sessionName,
  presence,
  autoview,
  autoread,
  botname,
  autobio,
  mode,
  prefix,
  autolike,
  mycode,
  author,
  packname,
  dev,
  DevDreaded,
  gcpresence,
  antionce,
session,
antitag,
antidelete
};
